version: '3.8'

services:
  usuarios-db:
    image: mysql:8.0
    container_name: usuarios_db
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:3306"
    volumes:
      - usuarios_data:/var/lib/mysql
    networks:
      - usuarios-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-p${DB_PASSWORD}"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  usuarios_data:

networks:
  usuarios-network:
    driver: bridge